import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial - Basics',
      items: ['tutorial-basics/create-a-document', 'tutorial-basics/create-a-blog-post', 'tutorial-basics/create-a-page', 'tutorial-basics/deploy-your-site', 'tutorial-basics/markdown-features'],
    },
    {
      type: 'category',
      label: 'Module 01 - ROS 2',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-01-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 02 - Digital Twin',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-02-digital-twin',
        },
      ],
    },
    // START: New Module 3 Entry
    {
      type: 'category',
      label: 'Module 03 - AI-Robot Brain (NVIDIA Isaac™)', // Display label for the module
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-03-isaac', // This should match the folder name in my-book/docs
        },
      ],
    },
    // START: New Module 4 Entry
    {
      type: 'category',
      label: 'Module 04 - Vision-Language-Action (VLA)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-04-vla', // This should match the folder name in my-book/docs
        },
      ],
    },
    // END: New Module 4 Entry
    // END: New Module 3 Entry
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
