import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
  
    {
      type: 'category',
      label: 'Module 01 - ROS 2',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-01-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 02 - Digital Twin',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-02-digital-twin',
        },
      ],
    },
    // START: New Module 3 Entry
    {
      type: 'category',
      label: 'Module 03 - AI-Robot Brain (NVIDIA Isaac™)', // Display label for the module
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-03-isaac', // This should match the folder name in my-book/docs
        },
      ],
    },
    // START: New Module 4 Entry
    {
      type: 'category',
      label: 'Module 04 - Vision-Language-Action (VLA)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-04-vla', // This should match the folder name in my-book/docs
        },
      ],
    },
    // END: New Module 4 Entry
    // END: New Module 3 Entry
  ],

};

export default sidebars;
